[package]
name = "example_diesel"
version = "0.1.0"
authors = ["Camilo Santos <camilossantos.2809@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version="1.4.5", features=["postgres"]}
dotenv = "0.15.0"
